site_name: NutriPlanner

repo_name: "2023.2-NutriPlanner"
repo_url: "https://github.com/mdsreq-fga-unb/2023.2-NutriPlanner"

theme:
  name: material
  language: "pt"
  favicon: docs_separados/assets/logo.png  
  icon:
    logo: material/food-variant
    repo: fontawesome/brands/github
  palette:
    primary: "blue"
    accent: "blue"
  font:
    text: "Montserrat"
    code: "sans-serif"

extra_css:
  - stylesheets/styles.css

nav:
  - Início: index.md
  - Visão do Produto e projeto:
    - Visão do produto: visao_geral_produto/visao_produto.md
    - Visão do Projeto: visao_projeto/visao_do_projeto.md
    - Processo de Desenvolvimento: processo_desenvolvimento/processo.md
  - Entrega do Produto: 
    - Proposta de MVP: produto/mvp/prop_mvp.md
    - Backlog SAFe: produto/backlog/backlog_safe.md
    - Definition of Done (DoD): produto/dod/dod.md
    - Definition of Ready (DoR): produto/dor/dor.md
    - Critérios de Aceitação: produto/criterios_aceit/criterios.md
  - Entregas das unidades:
    - Unidade 1:
      - Lições Aprendidas: licoes_aprendidas/licoes_01.md
      - História da Facção: docs_separados/historia.md
      - Visão do Produto: visao_geral_produto/slide_01.md
      - Visão do Processo: visao_geral_produto/slide_02.md
    - Unidade 2:
      - Lições Aprendidas: licoes_aprendidas/licoes_02.md
      - Apresentação backlog: visao_projeto/slide_01.md
      - VeriVal -> Equipe "Tanás": docs_separados/verival_tanas.md
    - Unidade 3:
      - Lições Aprendidas: licoes_aprendidas/licoes_03.md
      - Product Backlog Building: docs_separados/pbb.md
      - User Story Mapping: docs_separados/usm.md
      - VeriVal - PBB - GL: docs_separados/verival_gl.md
      - BDD: docs_separados/bdd.md
    - Unidade 4:
      - Lições Aprendidas: licoes_aprendidas/licoes_04.md
      - Casos de Uso: docs_separados/casos_uso.md
      - VeriVal - UC - GL: docs_separados/verival_UC_gl.md
    - Referências: referencias/referencias.md
    - Vídeos: videos/videos.md
  - Reuniões: 
    - Reuniões Gerais da Equipe:
      - Ata 1 (05/10/2023): atas_reunioes_gerais/ata_1.md
      - Ata 2 (07/10/2023): atas_reunioes_gerais/ata_2.md
      - Ata 3 (12/10/2023): atas_reunioes_gerais/ata_3.md
      - Ata 4 (16/10/2023): atas_reunioes_gerais/ata_4.md
      - Ata 5 (17/10/2023): atas_reunioes_gerais/ata_5.md
      - Ata 6 (08/11/2023): atas_reunioes_gerais/ata_6.md
      - Ata 7 (10/11/2023): atas_reunioes_gerais/ata_7.md
      - Reuniões e Templates: docs_separados/reunioes_templates.md
    - Alinhamentos com Cliente:
      - Relatório de Considerações (08/10/2023): relatorios_consideracoes_cliente/relatorio-08-10-2023.md
      - Relatório de Considerações (09/11/2023): relatorios_consideracoes_cliente/relatorio-09-11-2023.md